# Preparing Data for Cleaning

In [103]:
# import libraries
import pandas as pd
import numpy as np

In [104]:
# read in dataset
df = pd.read_csv('fifa21 raw data v2.csv')
df.sample(10)

ID              Name                     LongName  ... DEF PHY Hits
4229   255891         B. Šutalo                 Boško Šutalo  ...  74  66   63
11966  237080      S. Evangelou           Stefanos Evangelou  ...  65  66    4
12988  222923    F. Fumu Tamuzo  François-Xavier Fumu Tamuzo  ...  32  57    4
10312  193958          L. Brown                    Lee Brown  ...  62  76    4
15687  250929         P. Pyrdoł                 Piotr Pyrdoł  ...  22  40    1
407    216388  A. Saint-Maximin          Allan Saint-Maximin  ...  25  63  486
16303  257872        G. Thomson               George Thomson  ...  33  52    8
14405  236689      K. Al Samiri             Khaled Al Samiri  ...  59  56    3
12324  253534         D. Angles                 Diego Angles  ...  59  52    2
118    211256     N. Tagliafico           Nicolás Tagliafico  ...  82  79  171

[10 rows x 77 columns]

In [105]:
df.shape

(18979, 77)

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   ID                18979 non-null  int64 
 1   Name              18979 non-null  object
 2   LongName          18979 non-null  object
 3   photoUrl          18979 non-null  object
 4   playerUrl         18979 non-null  object
 5   Nationality       18979 non-null  object
 6   Age               18979 non-null  int64 
 7   ↓OVA              18979 non-null  int64 
 8   POT               18979 non-null  int64 
 9   Club              18979 non-null  object
 10  Contract          18979 non-null  object
 11  Positions         18979 non-null  object
 12  Height            18979 non-null  object
 13  Weight            18979 non-null  object
 14  Preferred Foot    18979 non-null  object
 15  BOV               18979 non-null  int64 
 16  Best Position     18979 non-null  object
 17  Joined      

In [107]:
# create copy of Dataframe
fifa = df.copy()

# Cleaning Data

## Check Club Column

In [108]:
# should be string
fifa['Club'].dtype

dtype('O')

In [109]:
# fifa['Club'].unique() has leading spaces
fifa['Club'] = fifa['Club'].str.strip()
fifa['Club'].unique()

array(['FC Barcelona', 'Juventus', 'Atlético Madrid', 'Manchester City',
       'Paris Saint-Germain', 'FC Bayern München', 'Liverpool',
       'Real Madrid', 'Chelsea', 'Tottenham Hotspur', 'Inter', 'Napoli',
       'Borussia Dortmund', 'Manchester United', 'Arsenal', 'Lazio',
       'Leicester City', 'Borussia Mönchengladbach', 'Real Sociedad',
       'Atalanta', 'Olympique Lyonnais', 'Milan', 'Villarreal CF',
       'RB Leipzig', 'Cagliari', 'Ajax', 'SL Benfica', 'AS Monaco',
       'Wolverhampton Wanderers', 'Everton', 'Fiorentina', 'FC Porto',
       'RC Celta', 'Torino', 'Sevilla FC', 'Grêmio', 'Real Betis', 'Roma',
       'Newcastle United', 'Eintracht Frankfurt', 'Valencia CF',
       'Medipol Başakşehir FK', 'Inter Miami', 'Bayer 04 Leverkusen',
       'Levante UD', 'Crystal Palace', 'Athletic Club de Bilbao',
       'Shanghai SIPG FC', 'VfL Wolfsburg',
       'Guangzhou Evergrande Taobao FC', 'Al Shabab',
       'Olympique de Marseille', 'Los Angeles FC',
       'Beijing Sino

## Check Contract Column

In [110]:
# should be string
fifa['Contract'].dtype

dtype('O')

In [111]:
fifa['Contract'].unique() # inconsistent formatting

array(['2004 ~ 2021', '2018 ~ 2022', '2014 ~ 2023', '2015 ~ 2023',
       '2017 ~ 2022', '2017 ~ 2023', '2018 ~ 2024', '2014 ~ 2022',
       '2018 ~ 2023', '2016 ~ 2023', '2013 ~ 2023', '2011 ~ 2023',
       '2009 ~ 2022', '2005 ~ 2021', '2011 ~ 2021', '2015 ~ 2022',
       '2017 ~ 2024', '2010 ~ 2024', '2012 ~ 2021', '2019 ~ 2024',
       '2015 ~ 2024', '2017 ~ 2025', '2020 ~ 2025', '2019 ~ 2023',
       '2008 ~ 2023', '2015 ~ 2021', '2020 ~ 2022', '2012 ~ 2022',
       '2016 ~ 2025', '2013 ~ 2022', '2011 ~ 2022', '2012 ~ 2024',
       '2016 ~ 2021', '2012 ~ 2023', '2008 ~ 2022', '2019 ~ 2022',
       '2017 ~ 2021', '2013 ~ 2024', '2020 ~ 2024', '2010 ~ 2022',
       '2020 ~ 2021', '2011 ~ 2024', '2020 ~ 2023', '2014 ~ 2024',
       '2013 ~ 2026', '2016 ~ 2022', '2010 ~ 2021', '2013 ~ 2021',
       '2019 ~ 2025', '2018 ~ 2025', '2016 ~ 2024', '2018 ~ 2021',
       '2009 ~ 2024', '2007 ~ 2022', 'Jun 30, 2021 On Loan',
       '2009 ~ 2021', '2019 ~ 2021', '2019 ~ 2026', 'Free', '2012 ~ 

In [112]:
# look for rows with different formatting
for index, row in fifa.iterrows():
    if 'On Loan' in row['Contract'] or 'Free' in row['Contract']:
        print(row['Contract'])

Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Free
Free
Free
Free
Free
Free
Free
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Free
Free
Free
Jun 30, 2021 On Loan
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Free
Free
Free
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Jan 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Dec 31, 2020 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Jun 30, 2021 On Loan
Free
Jun 30, 2021 On Loan
Free
Free
Free

In [113]:
# function to specify start date, end date, and contract length given contract not Free or On loan

def extract_contract_info(contract):
    """function to specify start date, end date, and contract length given contract not Free or On loan"""
    if contract == 'Free' or 'On Loan' in contract:
        start_date = np.nan
        end_date = np.nan
        contract_length = 0
    else:
        start_date, end_date = contract.split(' ~ ')
        start_year = int(start_date[:4])
        end_year = int(end_date[:4])
        contract_length = end_year - start_year
    return start_date, end_date, contract_length

# apply function to Contract column and create new columns
new_cols = ['Contract Start', 'Contract End', 'Contract Length(years)']
new_data = fifa['Contract'].apply(lambda x: pd.Series(extract_contract_info(x)))

# insert new cols after Contract column
for i in range(len(new_cols)):
    fifa.insert(loc = fifa.columns.get_loc('Contract') + 1 + i, column = new_cols[i], value = new_data[i])

In [114]:
fifa.sample(3)

ID         Name        LongName  ... DEF PHY Hits
16121  235493  T. Abdullah  Tareq Abdullah  ...  58  62    2
5770   214110  J. Cuadrado   José Cuadrado  ...  46  66    2
1670   193881   F. Đuričić   Filip Đuričić  ...  42  55   29

[3 rows x 80 columns]

In [115]:
def contract_category(contract):
    """function witll categorize contract status"""
    if contract == 'Free':
        return 'Free'
    elif 'On Loan' in contract:
        return 'On Loan'
    else:
        return 'Contract'
    
# Add status category column
fifa.insert(loc = fifa.columns.get_loc('Contract Length(years)') + 1, column = 'Contract Status', value = fifa['Contract'].apply(contract_category))

In [116]:
fifa.sample(3)

ID         Name          LongName  ... DEF PHY Hits
16830  256075    L. Rangel       Luis Rangel  ...  55  64  NaN
7222   210917   M. Fossati     Marco Fossati  ...  53  67    3
14215  258389  V. Besuijen  Vicente Besuijen  ...  19  42    5

[3 rows x 81 columns]

## Check Height Column

In [117]:
fifa['Height'].dtype

dtype('O')

In [118]:
fifa['Height'].unique()

array(['170cm', '187cm', '188cm', '181cm', '175cm', '184cm', '191cm',
       '178cm', '193cm', '185cm', '199cm', '173cm', '168cm', '176cm',
       '177cm', '183cm', '180cm', '189cm', '179cm', '195cm', '172cm',
       '182cm', '186cm', '192cm', '165cm', '194cm', '167cm', '196cm',
       '163cm', '190cm', '174cm', '169cm', '171cm', '197cm', '200cm',
       '166cm', '6\'2"', '164cm', '198cm', '6\'3"', '6\'5"', '5\'11"',
       '6\'4"', '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"',
       '5\'4"', '201cm', '158cm', '162cm', '161cm', '160cm', '203cm',
       '157cm', '156cm', '202cm', '159cm', '206cm', '155cm'], dtype=object)

In [119]:
def height_conversion(height):
    """function to standardize height in cm"""
    if 'cm' in height:
        return int(height.strip(' cm'))
    else:
        feet, inches = height.split("'")
        total_inches = int(feet) * 12 + int(inches.strip('"'))
        return round(total_inches * 2.54)
    
# apply height conversion fn to height column
fifa['Height'] = fifa['Height'].apply(height_conversion)

In [120]:
fifa['Height'].unique()

array([170, 187, 188, 181, 175, 184, 191, 178, 193, 185, 199, 173, 168,
       176, 177, 183, 180, 189, 179, 195, 172, 182, 186, 192, 165, 194,
       167, 196, 163, 190, 174, 169, 171, 197, 200, 166, 164, 198, 201,
       158, 162, 161, 160, 203, 157, 156, 202, 159, 206, 155])

In [121]:
fifa = fifa.rename(columns = {'Height': 'Height(cm)'})
fifa.sample(1)

ID      Name       LongName  ... DEF PHY Hits
17678  226942  O. Çapar  Oğuzhan Çapar  ...  59  50  NaN

[1 rows x 81 columns]

## Check Weight Column

In [122]:
fifa['Weight'].dtype

dtype('O')

In [123]:
fifa['Weight'].unique()

array(['72kg', '83kg', '87kg', '70kg', '68kg', '80kg', '71kg', '91kg',
       '73kg', '85kg', '92kg', '69kg', '84kg', '96kg', '81kg', '82kg',
       '75kg', '86kg', '89kg', '74kg', '76kg', '64kg', '78kg', '90kg',
       '66kg', '60kg', '94kg', '79kg', '67kg', '65kg', '59kg', '61kg',
       '93kg', '88kg', '97kg', '77kg', '62kg', '63kg', '95kg', '100kg',
       '58kg', '183lbs', '179lbs', '172lbs', '196lbs', '176lbs', '185lbs',
       '170lbs', '203lbs', '168lbs', '161lbs', '146lbs', '130lbs',
       '190lbs', '174lbs', '148lbs', '165lbs', '159lbs', '192lbs',
       '181lbs', '139lbs', '154lbs', '157lbs', '163lbs', '98kg', '103kg',
       '99kg', '102kg', '56kg', '101kg', '57kg', '55kg', '104kg', '107kg',
       '110kg', '53kg', '50kg', '54kg', '52kg'], dtype=object)

In [124]:
def weight_conversion(weight):
    """function to standardize weight in kg"""
    if 'kg' in weight:
        return int(weight.strip('kg'))
    else:
        lbs = int(weight.strip('lbs'))
        return round(lbs/2.205)
    
# apply weight conversion to weight column
fifa['Weight'] = fifa['Weight'].apply(weight_conversion)

In [125]:
fifa['Weight'].unique()

array([ 72,  83,  87,  70,  68,  80,  71,  91,  73,  85,  92,  69,  84,
        96,  81,  82,  75,  86,  89,  74,  76,  64,  78,  90,  66,  60,
        94,  79,  67,  65,  59,  61,  93,  88,  97,  77,  62,  63,  95,
       100,  58,  98, 103,  99, 102,  56, 101,  57,  55, 104, 107, 110,
        53,  50,  54,  52])

In [126]:
fifa = fifa.rename(columns = {'Weight': 'Weight(kg)'})

In [127]:
fifa.sample(1)

ID        Name          LongName  ... DEF PHY Hits
16934  255883  E. Escobar  Ezequiel Escobar  ...  35  56  NaN

[1 rows x 81 columns]

## Check Loan Date End

In [128]:
fifa['Loan Date End'].dtype

dtype('O')

In [129]:
fifa['Loan Date End'].unique()

array([nan, '30-Jun-21', '31-Dec-20', '30-Jan-21', '30-Jun-22',
       '31-May-21', '05-Jul-21', '31-Dec-21', '01-Jul-21', '01-Jan-21',
       '31-Aug-21', '31-Jan-21', '30-Dec-21', '23-Jun-21', '03-Jan-21',
       '27-Nov-21', '17-Jan-21', '30-Jun-23', '31-Jul-21', '22-Nov-20',
       '31-May-22', '30-Dec-20', '04-Jan-21', '30-Nov-20', '01-Aug-21'],
      dtype=object)

In [130]:
on_loan = fifa[fifa['Contract Status'] == 'On Loan']
on_loan[['Contract', 'Contract Status', 'Loan Date End']]
# acceptable null values, non-null are formatted correctly

Contract Contract Status Loan Date End
205    Jun 30, 2021 On Loan         On Loan     30-Jun-21
248    Jun 30, 2021 On Loan         On Loan     30-Jun-21
254    Jun 30, 2021 On Loan         On Loan     30-Jun-21
302    Jun 30, 2021 On Loan         On Loan     30-Jun-21
306    Jun 30, 2021 On Loan         On Loan     30-Jun-21
...                     ...             ...           ...
18472  Aug 31, 2021 On Loan         On Loan     31-Aug-21
18571  Jun 30, 2021 On Loan         On Loan     30-Jun-21
18600  Dec 31, 2020 On Loan         On Loan     31-Dec-20
18622  Dec 31, 2020 On Loan         On Loan     31-Dec-20
18680  Dec 31, 2020 On Loan         On Loan     31-Dec-20

[1013 rows x 3 columns]

## Check Player's weak foot rating and skill move rating

In [131]:
fifa['W/F'].dtype

dtype('O')

In [132]:
fifa['W/F'].unique()

array(['4 ★', '3 ★', '5 ★', '2 ★', '1 ★'], dtype=object)

In [133]:
# remove star from weak foot column in case of performing calculations
fifa['W/F'] = fifa['W/F'].str.replace('★', '').astype('int')
fifa['W/F'].sample(5)

10637    3
15957    3
3639     3
8244     2
8326     4
Name: W/F, dtype: int64

In [134]:
fifa['SM'].dtype

dtype('O')

In [135]:
fifa['SM'].unique()

array(['4★', '5★', '1★', '2★', '3★'], dtype=object)

In [136]:
# remove star from SM column in case of performing calculations
fifa['SM'] = fifa['SM'].str.replace('★', '').astype('int')
fifa['SM'].sample(5)

16335    2
13492    3
18848    2
2492     2
16683    2
Name: SM, dtype: int64